### PR TITLE
fix: css code now works even without head tag

### LINKED ISSUE #7: CSS insertion fails when there is no head tag in the html buffer
**Describe the bug**
When the html code does not contain a `<head>` tag, the CSS code is not inserted in the final code displayed by the Preview component.

**To Reproduce**
1. On the editor page
2. Add HTML code without a `<head>` tag
3. Add CSS code in the CSS buffer
4. See that the CSS is not applied to the Preview

**Expected behavior**
CSS should be applied even without the `<head>` tag present in the HTML buffer.

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Browser safari, chrome, firefox

### PR DESCRIPTION
**Pull request by akashdoppalapudi**
- fixes #7 
- solved by adding style tag at the end of the html document

### CODE REVIEW

File: src/components/Preview.tsx [hunk 1]
```diff
@@ -3,13 +3,8 @@ import CodeContext from "../contexts/CodeContext";
 
 const Preview = () => {
   const { html, css, js } = useContext(CodeContext);
-  const linkedHtml = html.htmlCode.replace(
-    "</head>",
-    `<style>${css.cssCode
-      .replace(/ /g, "")
-      .replace(/  /g, "")
-      .replace(/\n/g, "")}</style></head>`
```
Comment (notshriram) [inline src/components/Preview.tsx:11]: So we don't need to do these anymore?

**Comment by notshriram** [comment]
works fine on my machine, lgtm 👍

**Review by notshriram — APPROVED** [review]
lgtm
